# Generated by Django 4.2.6 on 2024-01-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='doa',
            new_name='DOA',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='DOB',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='height',
            new_name='Height',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_checkup',
            new_name='Last_Checkup',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_name',
            new_name='Patient_Name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='Patient_id',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='type_of_disease',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='threshold_bp_rate',
            new_name='Threshold_BP_Rate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='threshold_co2_rate',
            new_name='Threshold_CO2_Rate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='threshold_heart_rate',
            new_name='Threshold_Heart_Rate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='threshold_spo2_rate',
            new_name='Threshold_SPO2_Rate',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='weight',
            new_name='Weight',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.AddField(
            model_name='patient',
            name='Address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patient',
            name='Blood_Pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Blood_Type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='Email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='Emergency_Contact_Number',
            field=models.CharField(default='1234567890', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Insurance_Provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Phone_Number',
            field=models.CharField(default='1234567890', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='Policy_Number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Respiration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='Sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Non-binary')], default='M', max_length=10),
            preserve_default=False,
        ),
    ]
