# Generated by Django 4.2.6 on 2023-11-26 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor',
            new_name='user',
        ),
    ]
