# Generated by Django 4.2.6 on 2023-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0002_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='userid',
        ),
        migrations.AlterField(
            model_name='timeline',
            name='time',
            field=models.TimeField(),
        ),
    ]
