# Generated by Django 4.2.6 on 2024-01-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0002_rename_age_patient_age_rename_doa_patient_doa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
