# Generated by Django 4.2.6 on 2023-11-26 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0002_rename_doctor_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
    ]
