# Generated by Django 4.2.6 on 2023-11-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0003_remove_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
    ]
