# Generated by Django 4.2.6 on 2023-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theGuardian', '0004_alter_doctor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='shrikanth', max_length=20),
            preserve_default=False,
        ),
    ]
